import type { Product, Category, Testimonial, Banner } from "@/types";


// ---- Categories ----
export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Fashion & Apparel",
    slug: "fashion",
    description: "Trending styles and designer collections",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&q=80",
    icon: "shirt",
    productCount: 245,
  },
  {
    id: "cat-2",
    name: "Electronics & Tech",
    slug: "electronics",
    description: "Latest gadgets and smart devices",
    image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&q=80",
    icon: "laptop",
    productCount: 189,
  },
  {
    id: "cat-3",
    name: "Home & Living",
    slug: "home-living",
    description: "Furniture, decor and essentials",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=400&q=80",
    icon: "home",
    productCount: 312,
  },
  {
    id: "cat-4",
    name: "Beauty & Wellness",
    slug: "beauty",
    description: "Skincare, makeup and self-care",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&q=80",
    icon: "sparkles",
    productCount: 178,
  },
  {
    id: "cat-5",
    name: "Sports & Outdoors",
    slug: "sports",
    description: "Gear up for any adventure",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80",
    icon: "dumbbell",
    productCount: 156,
  },
  {
    id: "cat-6",
    name: "Books & Media",
    slug: "books",
    description: "Bestsellers and new releases",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80",
    icon: "book-open",
    productCount: 423,
  },
];

// ---- Products ----
export const products: Product[] = [
  {
    id: "prod-1",
    name: "Premium Wireless Noise-Cancelling Headphones",
    slug: "premium-wireless-headphones",
    description: "Immerse yourself in pure acoustic bliss with our Premium Wireless Headphones. Engineered with advanced state-of-the-art Active Noise Cancellation (ANC) technology, these headphones filter out up to 98% of ambient noise, making them the ultimate companion for long flights, noisy commutes, or focused work sessions. The custom-tuned 40mm drivers deliver rich, deep bass and crystal-clear highs, bringing your favorite music to life like never before. With a massive 40-hour battery life and rapid charging capabilities, you'll never be without your soundtrack.",
    shortDescription: "Studio-quality sound with 40-hour battery and industry-leading ANC technology.",
    price: 32900,
    originalPrice: 43900,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80", "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80"],
    category: categories[1],
    subcategory: "Audio",
    variants: [
      { id: "v1", name: "Midnight Black", type: "color", value: "black", colorHex: "#1a1a2e", stock: 45, sku: "PWH-BLK" },
      { id: "v2", name: "Pearl White", type: "color", value: "white", colorHex: "#f8f9fa", stock: 32, sku: "PWH-WHT" },
    ],
    tags: ["wireless", "noise-cancelling", "premium", "bestseller"],
    rating: 4.8,
    reviewCount: 1247,
    sku: "PWH-001",
    stock: 105,
    isFeatured: true,
    isBestseller: true,
    brand: "SoundElite",
    specifications: { "Driver Size": "40mm", "ANC": "Hybrid Active", "Battery": "40 Hours", "Bluetooth": "5.3", "Charging": "USB-C Fast Charge" },
    createdAt: "2025-11-15",
  },
  {
    id: "prod-2",
    name: "Classic Chronograph Leather Watch",
    slug: "classic-leather-watch",
    description: "Elevate your personal style with the Classic Chronograph Leather Watch. This timepiece is a masterpiece of precision engineering, featuring a genuine Swiss-made quartz movement encased in a high-grade 316L stainless steel body. The dial is protected by scratch-resistant sapphire crystal glass, ensuring clarity and durability for years to come. Complemented by a handcrafted Italian full-grain leather strap that ages beautifully over time, this watch is the perfect blend of heritage design and modern reliability.",
    shortDescription: "Timeless Swiss movement timepiece with genuine Italian leather and sapphire crystal.",
    price: 20500,
    originalPrice: 27000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80"],
    category: categories[0],
    subcategory: "Watches",
    variants: [
      { id: "v4", name: "Cognac Brown", type: "color", value: "brown", colorHex: "#8B4513", stock: 50, sku: "CLW-BRN" },
      { id: "v5", name: "Obsidian Black", type: "color", value: "black", colorHex: "#2d2d2d", stock: 65, sku: "CLW-BLK" },
    ],
    tags: ["luxury", "watch", "leather", "swiss"],
    rating: 4.9,
    reviewCount: 856,
    sku: "CLW-001",
    stock: 155,
    isFeatured: true,
    isBestseller: true,
    brand: "Chronos",
    specifications: { "Movement": "Swiss Quartz", "Case": "316L Stainless Steel", "Glass": "Sapphire Crystal", "Water Resistance": "5 ATM", "Strap": "Italian Leather" },
    createdAt: "2025-10-20",
  },
  {
    id: "prod-n1",
    name: "Premium Cotton Printed Panjabi",
    slug: "premium-cotton-panjabi",
    description: "Experience the perfect blend of tradition and comfort with our Premium Cotton Printed Panjabi. Handcrafted from the finest long-staple Egyptian cotton, this Panjabi features intricate digital prints inspired by heritage motifs. The breathable fabric ensures maximum comfort under the tropical sun, making it an ideal choice for Friday prayers, weddings, or festive Boishakhi celebrations. The slim-fit design provides a modern silhouette while maintaining traditional elegance.",
    shortDescription: "Elegant traditional wear crafted from breathable high-thread-count Egyptian cotton.",
    price: 4500,
    originalPrice: 6500,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1706646545119-af67fd26ec49?w=800&q=80"],
    category: categories[0],
    subcategory: "Traditional Wear",
    variants: [
      { id: "v-n1", name: "S", type: "size", value: "S", stock: 20, sku: "PCP-S" },
      { id: "v-n2", name: "M", type: "size", value: "M", stock: 35, sku: "PCP-M" },
      { id: "v-n3", name: "L", type: "size", value: "L", stock: 30, sku: "PCP-L" },
    ],
    tags: ["traditional", "panjabi", "cotton", "eid", "boishakh"],
    rating: 4.7,
    reviewCount: 320,
    sku: "PCP-001",
    stock: 85,
    isNew: true,
    brand: "Heritage Threads",
    specifications: { "Material": "100% Egyptian Cotton", "Fit": "Modern Slim Fit", "Print": "Eco-friendly Digital", "Collar": "Mandarin Style" },
    createdAt: "2026-03-15",
  },
  {
    id: "prod-n2",
    name: "Designer Jamdani Silk Saree",
    slug: "designer-jamdani-saree",
    description: "Own a piece of living heritage with our Designer Jamdani Silk Saree. Traditionally hand-woven by master artisans in Sonargaon, this saree features the iconic 'panna hajar' (thousand emeralds) pattern. The lightweight silk-cotton blend offers a regal drape and sheer elegance, perfect for formal evening events and wedding guest attire. Each saree takes approximately six weeks to complete, ensuring you receive a unique garment of unparalleled craftsmanship.",
    shortDescription: "Masterfully hand-woven Jamdani saree with artisanal motifs and premium silk finish.",
    price: 18500,
    originalPrice: 25000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1610189012903-bf2e977f6b4d?w=800&q=80"],
    category: categories[0],
    subcategory: "Saree",
    variants: [
      { id: "v-n4", name: "Emerald Green", type: "color", value: "green", colorHex: "#004d40", stock: 5, sku: "DJS-GRN" },
      { id: "v-n5", name: "Royal Maroon", type: "color", value: "maroon", colorHex: "#800000", stock: 3, sku: "DJS-MRN" },
    ],
    tags: ["saree", "jamdani", "silk", "hand-woven", "traditional"],
    rating: 5.0,
    reviewCount: 45,
    sku: "DJS-001",
    stock: 8,
    isFeatured: true,
    brand: "SilkRoute",
    specifications: { "Fabric": "Silk-Cotton Blend", "Weave": "Hand-loomed Jamdani", "Length": "6.5 Meters", "Blouse Piece": "Included" },
    createdAt: "2026-03-20",
  },
  {
    id: "prod-n3",
    name: "Alpha 4K Mirrorless Camera v2",
    slug: "alpha-4k-mirrorless-camera",
    description: "Step into the world of professional photography with the Alpha 4K Mirrorless Camera. Equipped with a groundbreaking 33MP full-frame sensor and next-generation AI-powered autofocus, this camera captures stunning detail in both stills and cinematic 4K video. Whether you're a content creator, a wedding photographer, or a travel enthusiast, the compact body and dual card slots provide the versatility and reliability you need to master your craft.",
    shortDescription: "Professional 33MP full-frame sensor with AI-autofocus and cinematic 4K video.",
    price: 185000,
    originalPrice: 198000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80"],
    category: categories[1],
    subcategory: "Photography",
    variants: [
      { id: "v-n6", name: "Body Only", type: "style", value: "body", stock: 12, sku: "A4K-BOD" },
      { id: "v-n7", name: "With 24-70mm Lens", type: "style", value: "kit", stock: 8, sku: "A4K-KIT" },
    ],
    tags: ["camera", "mirrorless", "photography", "4k", "professional"],
    rating: 4.9,
    reviewCount: 156,
    sku: "A4K-001",
    stock: 20,
    isNew: true,
    isFeatured: true,
    brand: "LumixPro",
    specifications: { "Sensor": "33MP Full-frame CMOS", "Video": "4K 60p 10-bit", "ISO Range": "100-51200", "Autofocus": "AI Real-time Tracking" },
    createdAt: "2026-04-01",
  },
  {
    id: "prod-n4",
    name: "Tactile Mechanical Gaming Keyboard",
    slug: "tactile-mechanical-keyboard",
    description: "Precision at your fingertips. Our Tactile Mechanical Gaming Keyboard is built for speed and durability, featuring industry-leading brown mechanical switches rated for 80 million keystrokes. The customizable per-key RGB lighting and brushed aircraft-grade aluminum top plate make it as beautiful as it is powerful. Program macros, customize lighting profiles, and dominate the competition with zero-latency response times.",
    shortDescription: "Durable mechanical switches with per-key RGB and aluminum frame for elite gaming.",
    price: 12500,
    originalPrice: 15000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&q=80"],
    category: categories[1],
    subcategory: "Computer Accessories",
    variants: [
      { id: "v-n8", name: "Brown Switches", type: "style", value: "brown", stock: 50, sku: "TMK-BRW" },
      { id: "v-n9", name: "Blue Clicky Switches", type: "style", value: "blue", stock: 40, sku: "TMK-BLU" },
    ],
    tags: ["gaming", "keyboard", "mechanical", "rgb", "pc-gaming"],
    rating: 4.8,
    reviewCount: 420,
    sku: "TMK-001",
    stock: 90,
    isBestseller: true,
    brand: "GamerGear",
    specifications: { "Switches": "Mechanical Brown/Blue", "Layout": "Tenkeyless (TKL)", "Backlight": "16.8M RGB", "Interface": "USB-C Braided Cable" },
    createdAt: "2026-02-10",
  },
  {
    id: "prod-3",
    name: "Pro Ergonomic Mesh Office Chair",
    slug: "ergonomic-office-chair",
    description: "Revolutionize your work-from-home experience with the Pro Ergonomic Mesh Office Chair. Designed by chiropractic experts, this chair features a dynamic lumbar support system that adjusts to your every move, virtually eliminating back pain. The breathable Korean elastomeric mesh keeps you cool during long hours, while the 4D adjustable armrests and multi-position tilt-lock allow you to find the perfect posture for maximum productivity and focus.",
    shortDescription: "Scientific lumbar support with breathable mesh and 4D adjustability for all-day comfort.",
    price: 49000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1505797149-43b0076649d7?w=800&q=80"],
    category: categories[2],
    subcategory: "Office Furniture",
    variants: [
      { id: "v7", name: "Steel Gray", type: "color", value: "gray", colorHex: "#36454F", stock: 20, sku: "EOC-CHR" },
      { id: "v8", name: "Midnight Blue", type: "color", value: "blue", colorHex: "#1e3a5f", stock: 15, sku: "EOC-BLU" },
    ],
    tags: ["ergonomic", "office", "comfort", "premium"],
    rating: 4.7,
    reviewCount: 632,
    sku: "EOC-001",
    stock: 35,
    isFeatured: true,
    brand: "ComfortPro",
    specifications: { "Mesh": "Korean Elastomeric", "Base": "Polished Aluminum", "Casters": "Dual-wheel Nylon", "Weight Capacity": "150kg" },
    createdAt: "2025-12-01",
  },
  {
    id: "prod-n5",
    name: "Solid Oak 6-Seater Dining Table",
    slug: "solid-oak-dining-table",
    description: "Make memories around the Solid Oak Dining Table. Crafted from premium sustainably sourced European white oak, this 6-seater table features a minimalist Scandinavian design that complements any modern interior. The hand-rubbed oil finish protects the wood while highlighting the natural beauty of the grain. Built with traditional mortise and tenon joinery, this table is an investment piece designed to last for generations of family gatherings.",
    shortDescription: "Handcrafted sustainable European oak dining table with minimalist Scandi-design.",
    price: 75000,
    originalPrice: 85000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=800&q=80"],
    category: categories[2],
    subcategory: "Furniture",
    variants: [
      { id: "v-n10", name: "Natural Oak", type: "color", value: "natural", colorHex: "#D2B48C", stock: 5, sku: "SOD-NAT" },
      { id: "v-n11", name: "Dark Walnut Finish", type: "color", value: "walnut", colorHex: "#5D4037", stock: 3, sku: "SOD-WAL" },
    ],
    tags: ["dining", "table", "oak", "furniture", "luxury"],
    rating: 4.9,
    reviewCount: 28,
    sku: "SOD-001",
    stock: 8,
    isFeatured: true,
    brand: "NordicHome",
    specifications: { "Material": "Solid White Oak", "Seating": "6 Persons", "Finish": "Natural Oil", "Dimensions": "180cm x 90cm x 75cm" },
    createdAt: "2026-03-01",
  },
  {
    id: "prod-n6",
    name: "Smart Ambient Floor Lamp",
    slug: "smart-ambient-floor-lamp",
    description: "Transform your living space with the Smart Ambient Floor Lamp. Offering 16 million colors and tunable white light from warm candle-glow to cool daylight, this lamp sets the perfect mood for reading, movie nights, or parties. Sync the lights with your music, control them via voice with Alexa or Google Home, or use the dedicated app to create custom schedules for a truly automated smart home lighting experience.",
    shortDescription: "RGBIC smart lamp with 16M colors, voice control, and dynamic music sync.",
    price: 8500,
    originalPrice: 12000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1513506496268-3dd9b11496b1?w=800&q=80"],
    category: categories[2],
    subcategory: "Lighting",
    variants: [
      { id: "v-n12", name: "Starlight Silver", type: "color", value: "silver", colorHex: "#C0C0C0", stock: 25, sku: "SFL-SLV" },
      { id: "v-n13", name: "Matte Black", type: "color", value: "black", colorHex: "#000000", stock: 30, sku: "SFL-BLK" },
    ],
    tags: ["lighting", "smart-home", "rgb", "ambient", "modern"],
    rating: 4.6,
    reviewCount: 189,
    sku: "SFL-001",
    stock: 55,
    isNew: true,
    brand: "LumenTech",
    specifications: { "Light Source": "RGBIC LED", "Brightness": "2000 Lumens", "Connectivity": "Wi-Fi + App", "Height": "160cm" },
    createdAt: "2026-03-10",
  },
  {
    id: "prod-n7",
    name: "Authentic English Willow Cricket Bat",
    slug: "english-willow-cricket-bat",
    description: "Master the crease with our Authentic English Willow Cricket Bat. Hand-selected from Grade 1+ English Willow, each bat features perfectly straight grains and a massive swell for explosive power. The semi-oval handle provides superior control for both front-foot drives and back-foot punches. Balanced to perfection with a light pick-up, this is the same quality used by top-tier international cricketers in the BPL and IPL.",
    shortDescription: "Grade 1+ hand-selected English Willow with explosive power and light pick-up.",
    price: 28500,
    originalPrice: 35000,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80"],
    category: categories[4],
    subcategory: "Cricket",
    variants: [
      { id: "v-n14", name: "Standard (1180-1200g)", type: "weight", value: "std", stock: 15, sku: "EWB-STD" },
      { id: "v-n15", name: "Lightweight (1150-1175g)", type: "weight", value: "light", stock: 10, sku: "EWB-LGHT" },
    ],
    tags: ["cricket", "sports", "willow", "professional", "bat"],
    rating: 4.9,
    reviewCount: 84,
    sku: "EWB-001",
    stock: 25,
    isFeatured: true,
    isBestseller: true,
    brand: "Kookaburra",
    specifications: { "Willow Grade": "1+ English Willow", "Grains": "8-12 Straight", "Sweet Spot": "Mid-Low", "Handle": "9-piece Cane" },
    createdAt: "2026-02-20",
  },
  {
    id: "prod-n8",
    name: "Elite Performance Gym Bag v3",
    slug: "elite-gym-bag",
    description: "The ultimate organization tool for your active lifestyle. The Elite Performance Gym Bag features a dedicated ventilated shoe compartment, a water-resistant wet pocket for post-workout gear, and a padded sleeve for your 14\" laptop. Built from ultra-durable 1000D ballistic nylon with reinforced stitching, this bag is designed to withstand the rigors of daily travel from office to gym while keeping your essentials organized and safe.",
    shortDescription: "Durable 1000D ballistic nylon bag with ventilated shoe compartment and laptop sleeve.",
    price: 5200,
    originalPrice: 7500,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80"],
    category: categories[4],
    subcategory: "Gym Gear",
    variants: [
      { id: "v-n16", name: "Deep Charcoal", type: "color", value: "charcoal", colorHex: "#36454F", stock: 45, sku: "EGB-CHR" },
      { id: "v-n17", name: "Electric Blue", type: "color", value: "blue", colorHex: "#0000FF", stock: 30, sku: "EGB-BLU" },
    ],
    tags: ["gym", "bag", "sports", "fitness", "water-resistant"],
    rating: 4.7,
    reviewCount: 312,
    sku: "EGB-001",
    stock: 75,
    isNew: true,
    brand: "FitGear",
    specifications: { "Material": "1000D Ballistic Nylon", "Volume": "45 Liters", "Zippers": "YKK Heavy Duty", "Shoe Pocket": "Ventilated" },
    createdAt: "2026-03-05",
  },
  {
    id: "prod-n9",
    name: "Hyaluronic Acid Multi-Mask Set",
    slug: "hyaluronic-acid-mask-set",
    description: "Rejuvenate your skin with our Hyaluronic Acid Multi-Mask Set. This collection includes 10 sheet masks infused with three weights of hyaluronic acid to penetrate deep into the skin's layers, providing instant and long-lasting hydration. Also features soothing aloe vera and brightening niacinamide to leave your skin looking plump, radiant, and dewy. Perfect for a weekly self-care ritual or as a rescue treatment for dry, tired skin.",
    shortDescription: "10-sheet intensive hydration set with HA, aloe vera, and brightening niacinamide.",
    price: 3500,
    originalPrice: 4800,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1552046122-03184de85e08?w=800&q=80"],
    category: categories[3],
    subcategory: "Skincare",
    variants: [
      { id: "v-n18", name: "Hydrating Set", type: "style", value: "hydrating", stock: 100, sku: "HAM-HYD" },
      { id: "v-n19", name: "Soothing Set", type: "style", value: "soothing", stock: 80, sku: "HAM-STH" },
    ],
    tags: ["skincare", "mask", "beauty", "hydration", "glow"],
    rating: 4.8,
    reviewCount: 540,
    sku: "HAM-001",
    stock: 180,
    isFeatured: true,
    brand: "GlowNature",
    specifications: { "Quantity": "10 Sheets", "Key Ingredients": "Hyaluronic Acid, Niacinamide", "Skin Types": "All", "Cruelty-Free": "Yes" },
    createdAt: "2026-03-25",
  },
  {
    id: "prod-n10",
    name: "The Alchemist (Hardcover Edition)",
    slug: "the-alchemist-hardcover",
    description: "A timeless masterpiece that continues to inspire millions worldwide. This deluxe hardcover edition of 'The Alchemist' by Paulo Coelho features a stunning gold-embossed cover and high-quality cream-colored paper. Follow the enchanting story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure but finds a far more rewarding one through self-discovery. A must-have for every bookstore and home library.",
    shortDescription: "Deluxe gold-embossed hardcover edition of Paulo Coelho's global spiritual masterpiece.",
    price: 1850,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80"],
    category: categories[5],
    subcategory: "Fiction",
    variants: [
      { id: "v-n20", name: "Hardcover", type: "style", value: "hard", stock: 50, sku: "ALC-HRD" },
    ],
    tags: ["book", "classic", "fiction", "inspiration", "bestseller"],
    rating: 4.9,
    reviewCount: 5600,
    sku: "ALC-001",
    stock: 100,
    isBestseller: true,
    brand: "Penguin Classics",
    specifications: { "Format": "Hardcover", "Pages": "208", "Author": "Paulo Coelho", "Language": "English" },
    createdAt: "2025-01-01",
  },
  {
    id: "prod-n11",
    name: "Classic Novels of Himu - Set",
    slug: "classic-himu-set",
    description: "Dive into the surreal world of Himu, the iconic character created by Humayun Ahmed. This 5-book set includes the most beloved titles like 'Himu', 'Hajari Chayay Himu', and 'Himu Ebong Ekti Russian Pari'. Each book is printed on high-quality offset paper with the original cover art. Perfect for any lover of Bengali literature, this set captures the essence of Dhaka's streets and the yellow-clad wanderer's philosophical journey.",
    shortDescription: "Curated 5-book collection of Humayun Ahmed's iconic yellow-clad wanderer series.",
    price: 2450,
    originalPrice: 3200,
    currency: "BDT",
    images: ["https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&q=80"],
    category: categories[5],
    subcategory: "Bengali Literature",
    variants: [
      { id: "v-n21", name: "Standard Set", type: "style", value: "set", stock: 30, sku: "HMS-SET" },
    ],
    tags: ["book", "bengali", "classic", "humayun-ahmed", "literature"],
    rating: 5.0,
    reviewCount: 890,
    sku: "HMS-001",
    stock: 45,
    isFeatured: true,
    isNew: true,
    brand: "Anyaprokash",
    specifications: { "Books": "5 Titles", "Language": "Bengali", "Format": "Paperback", "Paper": "Offset" },
    createdAt: "2026-03-12",
  },
];

// ---- Testimonials ----
export const testimonials: Testimonial[] = [
  { id: "t1", name: "Sadia Rahman", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80", role: "Verified Buyer", rating: 5, comment: "Absolutely love the quality! The headphones are incredible — best purchase I've made this year. Customer service was top-notch too." },
  { id: "t2", name: "Tahsan Khan", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80", role: "Verified Buyer", rating: 5, comment: "The watch is even more beautiful in person. Packaging was premium and shipping was incredibly fast. Will definitely order again!" },
  { id: "t3", name: "Farhana Islam", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80", role: "Verified Buyer", rating: 5, comment: "Finally found a store that actually delivers on quality. The skincare set transformed my routine. Everything feels so premium." },
  { id: "t4", name: "Abir Hossain", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80", role: "Verified Buyer", rating: 4, comment: "Great selection and competitive prices. The running shoes exceeded my expectations. Super fast delivery too!" },
];

// ---- Banners ----
export const banners: Banner[] = [
  { id: "b1", title: "Boishakhi Collection 2026", subtitle: "Fresh styles for a new season", image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=1200&q=80", link: "/shop?category=fashion", buttonText: "Shop Now", position: "hero" },
  { id: "b2", title: "Tech Deals Week", subtitle: "Up to 40% off electronics", image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=1200&q=80", link: "/shop?category=electronics", buttonText: "Explore Deals", position: "hero" },
  { id: "b3", title: "Free Shipping", subtitle: "On orders over ৳5,000", image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80", link: "/shop", buttonText: "Start Shopping", position: "inline" },
];

// ---- Brands ----
export const brands = [
  "SoundElite", "Chronos", "ComfortPro", "GlowNature", "VelocityX",
  "AudioSphere", "UrbanCarry", "TerraForm", "ZenGrip", "DeskElite", "PureHome",
];

// ---- Helper functions ----
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category.slug === categorySlug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getBestsellers(): Product[] {
  return products.filter((p) => p.isBestseller);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.name.toLowerCase().includes(q)
  );
}
